### ISSUE TITLE
运行move_watermask_location.py出错

### ISSUE THREAD

**Issue by upupbo** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-fake_data_generator#1]
cb@ceo-pc:~/code/ccf_ocr/2/fake_data_generator/chusai_fuyinwuxiao/first_train$ python move_watermask_location.py
0a5f692293f34acfb7fa006b910c2598_1.jpg
Traceback (most recent call last):
  File "move_watermask_location.py", line 149, in <module>
    m_run(img)
  File "move_watermask_location.py", line 101, in m_run
    father_cor, img_father = match_img(img_path, roi_img_path, tp_threshold)
  File "move_watermask_location.py", line 21, in match_img
    img_gray = cv2.cvtColor(img_rgb, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.1.1) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by upupbo** [comment]
0a5f692293f34acfb7fa006b910c2598_1.jpg
/home/cb/code/ccf_ocr/2/fake_data_generator/Train_DataSet_final/0a5f692293f34acfb7fa006b910c2598_1.jpg
/home/cb/code/ccf_ocr/2/fake_data_generator/chusai_fuyinwuxiao/first_train/chusai_watermask_template_bigger_1.jpg
目标文件图片不存在

**Comment by Mingtzge** [comment]
this issue is fixed.  -->8c8676035ec525a6e3c50ab90405a95418c7164b
