### ISSUE TITLE
请问二代身份证正反底纹图片是从哪来的？还有比赛用的水印模板图片是怎么获得的？

### ISSUE THREAD

**Issue by fjibj** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-fake_data_generator#2]
请问二代身份证正反底纹图片是从哪来的？还有比赛用的水印模板图片是怎么获得的？

**Comment by Mingtzge** [comment]
二代身份证正反底纹图片从网上就能下载，比赛用的水印模板图片，“复印无效”只有汉字和矩形框采用的是伪造，“禁止复印”是直接从水印打在空白处的图片上提取得到的
