### ISSUE TITLE
关于生成“复印无效”数据的问题

### ISSUE THREAD

**Issue by csaimd** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-fake_data_generator#3]
你好，非常感谢分享你们的方案和代码，有个问题请教下，生成复印无效数据集第一阶段的的数据集1的时候，choosed_imgs_10_2:"复印无效"水印打在空白处的图片(只有部分样本，用这些样本运行python move_watermask_location.py，只能得到几百张图片), 比赛中choosed_imgs_10_2中有多少样本，如果想要用更多的样本，需要自己去训练集中挑选出这些水印打在空白的地方的样本吗？谢谢

**Comment by Mingtzge** [comment]
你好，我们挑选出来的样本有1500多个。
想要更多的样本，需要从赛题数据中去挑选一下，可以写个脚本，用模板匹配的方法找到水印位置，再判断水印是否在空白处。

**Comment by csaimd** [comment]
可以分享一下吗，我的邮箱地址1757518843@qq.com

**Comment by GC-Tom** [comment]
请问可以分享吗 我邮箱：1157244203@qq.com

**Comment by Mingtzge** [comment]
整理了一下相关数据，已经上传百度云，链接: https://pan.baidu.com/s/1RqKKQU_WBCFv2sL_7ObjDw 提取码: mkay 自取吧。如果链接失效，就添加我为百度云盘好友吧，1713983016@qq.com，备注：“2019 CCF BDCI 仿真数据”
